(load-file "~/.emacs.d/conf/packages.conf.el")
(load-file "~/.emacs.d/conf/macros.conf.el")
(load-file "~/.emacs.d/conf/general.conf.el")
(load-file "~/.emacs.d/conf/theme.conf.el")
(load-file "~/.emacs.d/conf/helm.conf.el")
(load-file "~/.emacs.d/conf/projectile.conf.el")
(load-file "~/.emacs.d/conf/org.conf.el")
(load-file "~/.emacs.d/conf/webdev.conf.el")
